<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Render\Element;
use Drupal\ctek_common\Plugin\paragraphs\Behavior\ParagraphsBehaviorBase;
use Drupal\paragraphs\ParagraphInterface;

function ctek_common_preprocess(&$vars) {
  $entity = NULL;
  switch ($vars['theme_hook_original']) {
    case 'field':
      if (isset($vars['entity_type'])) {
        $entity = $vars['element']['#object'];
        $vars['attributes']['data-field-name'] = $vars['field_name'];
      }
      $vars['tag'] = isset($vars['element']['#tag']) ? $vars['element']['#tag'] : 'div';
      $vars['wrapper'] = isset($vars['element']['#wrapper']) ? $vars['element']['#wrapper'] : 'div';
      break;
    case 'node':
      if (isset($vars['node'])) {
        $entity = $vars['node'];
      }
      break;
    case 'paragraph':
      if (isset($vars['paragraph'])) {
        $entity = $vars['paragraph'];
        $vars['attributes']['data-paragraph-type'] = $entity->bundle();
        $tabs = [];
        if ($entity->bundle() === 'tabs') {
          foreach (Element::children($vars['content']['field_items']) as $index => $child) {
            $id = Html::getUniqueId('tab') . '-' . ($index + 1);
            $tab = $vars['content']['field_items'][$child]['#paragraph'];
            if ($tab instanceof ParagraphInterface && $tab->bundle() === 'tab') {
              $tabs[$id] = $tab->get('field_title')->getString();
              $vars['content']['field_items'][$child]['#attributes']['id'] = $id;
            }
          }
        }
        $vars['tabs'] = $tabs;
      }
      break;
  }
  if ($entity) {
    ctek_common_inject_template($vars, $entity);
  }
}

function ctek_common_inject_template(array &$vars, ContentEntityInterface $entity) {
  $vars['layout'] = ctek_common_get_layout($entity);
  if (
    $entity instanceof ParagraphInterface
    &&
    $entity->hasField('field_heading_type')
    &&
    $entity->hasField('field_title')
    &&
    isset($vars['field_name'])
    &&
    $vars['field_name'] === 'field_title'
  ) {
    $vars['tag'] = ctek_common_get_heading_tag($entity);
  }
}

function ctek_common_get_layout(ContentEntityInterface $entity) {
  $layout = NULL;
  if ($entity->hasField('field_layout')) {
    $layout = $entity->get('field_layout')->value;
  } elseif ($entity instanceof ParagraphInterface) {
    if ($parent = $entity->getParentEntity()) {
      $layout = ctek_common_get_layout($parent);
    }
  }
  return $layout;
}

function ctek_common_get_heading_tag(ContentEntityInterface $entity) {
  $tag = NULL;
  if ($entity->hasField('field_heading_type')) {
    $tag = $entity->get('field_heading_type')->value;
  }
  return $tag;
}

function ctek_common_preprocess_block(&$vars) {
  if (isset($vars['plugin_id'])) {
    /** @var \Drupal\ctek_common\Block\BlockEnhancerPluginManager $blockEnhancerManager */
    $blockEnhancerManager = \Drupal::service('plugin.manager.block_enhancer');
    $blockEnhancerManager->enhanceBlock($vars);
  }
}

function ctek_common_paragraph_view(array &$build, ParagraphInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\paragraphs\ParagraphsBehaviorManager $manager */
  $manager = \Drupal::service('plugin.manager.paragraphs.behavior');
  $definitions = $manager->getDefinitions();
  foreach (Element::children($build) as $child) {
    $field =& $build[$child];
    if (isset($field['#field_type']) && $field['#field_type'] === 'image' && $field['#formatter'] === 'image') {
      $parent = $entity;
      $imageStyle = NULL;
      do {
        if ($parent instanceof ParagraphInterface) {
          $parentParagraphType = $parent->getType();
          if (isset($definitions[$parentParagraphType])) {
            $paragraphBehaviorDefinition = $definitions[$parentParagraphType];
            if (is_subclass_of($paragraphBehaviorDefinition['class'], ParagraphsBehaviorBase::class)) {
              try {
                /** @var ParagraphsBehaviorBase $paragraphBehavior */
                $paragraphBehavior = $manager->createInstance($parentParagraphType);
                $imageStyle = $paragraphBehavior->getImageStyle($entity, $field, $parent, $display, $view_mode);
              } catch (\Exception $e) {

              }
            }
          }
          $parent = $parent->getParentEntity();
        } else {
          $parent = NULL;
        }
      } while ($imageStyle === NULL && $parent !== NULL);
      if ($imageStyle) {
        foreach (Element::children($field) as $image) {
          $field[$image]['#image_style'] = $imageStyle;
        }
      }
    }
    $parent = NULL;
    if (isset($field['#field_type']) && $field['#field_type'] === 'image' && $field['#formatter'] === 'responsive_image') {
      $parent = $entity;
      $imageStyle = NULL;
      do {
        if ($parent instanceof ParagraphInterface) {
          $parentParagraphType = $parent->getType();
          if (isset($definitions[$parentParagraphType])) {
            $paragraphBehaviorDefinition = $definitions[$parentParagraphType];
            if (is_subclass_of($paragraphBehaviorDefinition['class'], ParagraphsBehaviorBase::class)) {
              try {
                /** @var ParagraphsBehaviorBase $paragraphBehavior */
                $paragraphBehavior = $manager->createInstance($parentParagraphType);
                $imageStyle = $paragraphBehavior->getResponsiveImageStyle($entity, $field, $parent, $display, $view_mode);
              } catch (\Exception $e) {

              }
            }
          }
          $parent = $parent->getParentEntity();
        } else {
          $parent = NULL;
        }
      } while ($imageStyle === NULL && $parent !== NULL);
      if ($imageStyle) {
        foreach (Element::children($field) as $image) {
          $field[$image]['#responsive_image_style_id'] = $imageStyle;
        }
      }
    }
    $parent = NULL;
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function ctek_common_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['library'][] = 'ctek_common/drupal-behavior';
  $attachments['#attached']['drupalSettings']['env'] = $_ENV['CTEK_ENV'];
  if (\Drupal::currentUser()->hasPermission('access administration pages')) {
    $attachments['#attached']['library'][] = 'ctek_common/profiler';
  }
}
